// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-Tyw3NCUbyGc09TplYTn5D0iXoI51qY',
    appId: '1:917801962298:web:5d1d8f34a43c6de652de03',
    messagingSenderId: '917801962298',
    projectId: 'gym-flutter-u',
    authDomain: 'gym-flutter-u.firebaseapp.com',
    storageBucket: 'gym-flutter-u.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZDBrtA8JkilnBctW4Lncps07CqDmbMcI',
    appId: '1:917801962298:android:a71757b18151b06052de03',
    messagingSenderId: '917801962298',
    projectId: 'gym-flutter-u',
    storageBucket: 'gym-flutter-u.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZFw-cSGOSr57SC35MZq3ceD9RUc0iTcs',
    appId: '1:917801962298:ios:7a5f31ece6b603e352de03',
    messagingSenderId: '917801962298',
    projectId: 'gym-flutter-u',
    storageBucket: 'gym-flutter-u.appspot.com',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZFw-cSGOSr57SC35MZq3ceD9RUc0iTcs',
    appId: '1:917801962298:ios:a3ba7867ac9429c252de03',
    messagingSenderId: '917801962298',
    projectId: 'gym-flutter-u',
    storageBucket: 'gym-flutter-u.appspot.com',
    iosBundleId: 'com.example.gym.RunnerTests',
  );
}
